### ISSUE TITLE
Blender closes when trying to render a simulation

### ISSUE THREAD

**Issue by PavelBlend** [InteractiveComputerGraphics/BlenderPartioTools#4]
Unable to render fluid particles. They do not load or the blender closes.
This applies to rendering animations.

**Comment by janbender** [comment]
I tested this with Blender 2.80 and it worked for me. Do you have a newer/older version?

**Comment by PavelBlend** [comment]
This seems to be the mistake of the blender itself, not the addon. When rendering Cycles, the blender is very unstable if particles change. Blender version: 2.82
